### ISSUE TITLE
getValue() returns a string, even if maxItems is > 1

### ISSUE THREAD

**Issue by donpinkus** [machineboy2045/angular-selectize#101]
Selectize is supposed to return a string if maxItems = 1, and an array if maxitems > 1

```
Returns the value of the control. If multiple items can be selected (e.g. <select multiple>, this returns an array. If only one item can be selected, this returns a string.
```

Calling `.getValue()` on a `<selectize>` component always returns a string.
```
var selectizeInstance = $('selectize')[0].selectize;
var selectizeValue = selectizeInstance.getValue();
```

**Comment by machineboy2045** [comment]
If there's an issue with getValue(), you'll need to post it on the Selectize repository. Angular-Selectize is just a wrapper for Selectize

**Comment by donpinkus** [comment]
I'm referring to this <selectize> angular component :)

When you call .getValue() on a selectize component instantiated through jquery, getValue() works correctly

**Comment by machineboy2045** [comment]
I see. I'm not sure why that would be, on the other hand, you shouldn't use getValue() with angular-selectize. You should be working the the angular model.
