### ISSUE TITLE
Docs on which part of Selectize API is not supported

### ISSUE THREAD

**Issue by donpinkus** [machineboy2045/angular-selectize#103]
This is an extremely useful directive

There is a bit of a learning curve to which of selectize's API methods this directive does or does not support.

For example the docs say the only different is "options" in config. After digging I found this issue https://github.com/machineboy2045/angular-selectize/issues/94 where I learnt that the load callback, and some other methods aren't supported.

**Comment by machineboy2045** [comment]
It's expected the user will rely on Angular for loading the options. Note my latest comment on #94

**Comment by totycro** [comment]
In this case, could you document that one should rely on options?

In my case, the following happened:
* I checked this github page for documentation
* I clicked the link to the selectize documentation as it was suggested
* The documentation said to use the load callback
