### ISSUE TITLE
Changes to options model don't appear in dropdown immediately

### ISSUE THREAD

**Issue by donpinkus** [machineboy2045/angular-selectize#104]
If a user has already typed something into the input, and selectize's options change, these new options are not shown in the dropdown immediately.

Selectize has refreshOptions(false) to handle this. Does not appear that angular-selectize has an equivalent method (since we are using a model for options).

How should we have new options appear immediately in open dropdowns?

**Comment by machineboy2045** [comment]
https://github.com/machineboy2045/angular-selectize/commit/d0d3fbf1fcf5442bfb2512776791e126f6df034e
