### ISSUE TITLE
Use Angular Selectize without the Selectize tag for W3C Validation

### ISSUE THREAD

**Issue by mdmoura** [machineboy2045/angular-selectize#27]
Hello,

Is it possible to use angular selective without the selective tag since I think this create problems with validation?

Thank you,
Miguel

**Comment by machineboy2045** [comment]
Can you elaborate on what the validation issue is?

**Comment by mdmoura** [comment]
I meant W3C validation ... In my opinion Selectize is an improvement to an already existing HTML tag, so according to one of Angular creators, the select tag should be used.

It should be only use a selectize tag if this would be a complete new feature.

And then there is the W3C validation problem ...

**Comment by mdmoura** [comment]
Are you sure this is working? I had the following with a previous version of Angular Selectize:

    <select data-ng-model="subscriber.country" data-placeholder="Country" name="country" data-selectize="model.countries" data-options="model.countries.options"></select>

This stopped working the moment I updated to the current version ...

**Comment by machineboy2045** [comment]
I think you need to change `data-selectize="model.countries"` to just `data-selectize`

**Comment by mdmoura** [comment]
That didn't work ... BTW, model.countries is the following:

    $scope.model = {
      countries: {
        labelField: 'Name',      
        maxItems: 1,
        persist: false,
        required: true,
        valueField: 'Id'
      }
    };

**Comment by machineboy2045** [comment]
oh. in that case do `<select data-ng-model="subscriber.country" data-placeholder="Country" name="country" data-selectize config="model.countries" data-options="model.countries.options"></select>`

**Comment by mdmoura** [comment]
Yes, that solved it ... Thanks

**Comment by machineboy2045** [comment]
no problem
