### ISSUE TITLE
Allow using selectize API methods

### ISSUE THREAD

**Issue by Qwal** [machineboy2045/angular-selectize#30]
Hi. I can't see it in code but is there a way to access selectize instance so I could use selectize events & api? For example I'd like to do open().

**Comment by Qwal** [comment]
Sorry, I put console.log in onInitialize function and it doesn't work.

**Comment by machineboy2045** [comment]
Are you using v1.1.1?

**Comment by Qwal** [comment]
My bad. I had 1.1.0 Thanks!
