### ISSUE TITLE
Passing Array or Single property according to Maximum Number of Items

### ISSUE THREAD

**Issue by mdmoura** [machineboy2045/angular-selectize#32]
Hello,

I have the following select:

        <select data-ng-model="subscriber.country" name="country" data-selectize="model.countries">
            <option value="">Country</option>
            <option value="1">US</option>
            <option value="2">UK</option>
        </select>

When I submit this form the subscriber.country value is always an Array even if I set the maximum number of items equal to 1, e.g., a drop down list.

Shouldn't you be passing simply an item in this case an not an array?

Thank You,
Miguel

**Comment by machineboy2045** [comment]
This is fixed in the latest release.
