### ISSUE TITLE
Is there a way to get the written text from the selectize input?

### ISSUE THREAD

**Issue by maplesap** [machineboy2045/angular-selectize#33]
Is there an event listener for on input into the text field? I would like to capture the currently unselected text every time the user types something.

Similar to this in jQuery:

    $(".selectize-input_1").on('input', function() {
        var current_text = $(".selectize-input").val();
        $.get("/autocomplete", current_text, function(options) {
             // Set new autocomplete options for selectize
        });
    })

**Comment by machineboy2045** [comment]
You can get the selectize object like so:

```javascript
$scope.config = {
  onInitialize: function(selectize){
    // receives the selectize object as an argument
  },
  // maxItems: 1
}
```

Then use selectize's api/events

**Comment by naferoozi** [comment]
To get value and text see my answer here: http://stackoverflow.com/a/34718000/779238
