### ISSUE TITLE
Internet explorer freezes if two many values selected

### ISSUE THREAD

**Issue by masimplo** [machineboy2045/angular-selectize#4]
Hi,

I noticed that you are watching for model value changes and running refreshSelectize in every value change. Running this in IE11 with 200 options (countries) and about 10-15 selections runs the browser to the ground (it literally crashes after a while).
Here is a plunk fork demonstrating the issue. Try adding more than 7-10 countries in the selection (it happens with much less values if you add and remove a few times, but just making it more obvious this way)

http://plnkr.co/edit/N0uTQ18NW4v6bdV8K9HZ

**Comment by djalmaaraujo** [comment]
@machineboy2045 @masimakopoulos The plnkr doesn't exists anymore, is this already on master on the last release? We are having serious issues on the IE11.
