### ISSUE TITLE
Android keyboard appears

### ISSUE THREAD

**Issue by s-d-p** [machineboy2045/angular-selectize#41]
On Android, when the selector is touched, the keyboard input appears. I suspect this is because the generated input is of `type="text"`

				<selectize  ng-model="filters.min_bedrooms" 
							options="[
									{title:'0', id:0},
									{title:'1', id:1},
									{title:'2', id:2},
									]">
				</selectize>

Generates:

        <input type="text" autocomplete="off" tabindex="" style="width: 4px; opacity: 0; position: absolute; left: -10000px;">

**Comment by machineboy2045** [comment]
This behavior is the result of the underlying jQuery selectize plugin. So it's not something I can change since this repo is just an Angular wrapper around the jQuery plugin.
