### ISSUE TITLE
Updating model does not update selectize?

### ISSUE THREAD

**Issue by lapidus** [machineboy2045/angular-selectize#47]
How can I extend angular-selectize to update the selected items when I change the model?

```
$scope.myModel = ["Tag1", "Tag2"];
<selectize options='myOptions' ng-model="myModel"></selectize>
$scope.myModel = ["Tag1", "Tag2", "Tag3"];
```

Results in only Tag1, Tag2 showing.

**Comment by amytych** [comment]
See #48, I think it could help you :-)

**Comment by lapidus** [comment]
Oh, how very useful. Dziękuję
