### ISSUE TITLE
Min items

### ISSUE THREAD

**Issue by Bana0615** [machineboy2045/angular-selectize#50]
is there a way to do min items just as i would do max items?

**Comment by PhiLhoSoft** [comment]
Perhaps with a custom validator.

**Comment by Bana0615** [comment]
i mean using this directive its self...theres a max so shouldnt there be a min it would make things alot easier especially if i am using this for a single select and i want it to be required.

**Comment by PhiLhoSoft** [comment]
You should add the `required` attribute to your `selectize` component, and manage it like any required field in your form.
Somehow, it is not something that can be managed at the component level, it is about the state of the form itself.

**Comment by Bana0615** [comment]
That's true. But what if I have a mutli select and want to them to select
at least 3 options

**Comment by PhiLhoSoft** [comment]
Back to custom validator... Again, nothing prevents the user to select two options, fill other fields of the form, then go back to the combo to add another option.
It is the responsibility of the form to ensure it is valid, and prevent submitting. The best the component can do is to report it isn't valid according to your validator rules. Which can be more complex (eg. select at least two items above a given price, whatever).

**Comment by Bana0615** [comment]
ok then you can close this issue. i was just trying to help this get as
close to the jquery version of selectize as possible.

**Comment by PhiLhoSoft** [comment]
Note: I am just a simple user like you, trying to help others, and the project owner by answering to issues. So I can't close the issue.
I think you can close it yourself: I think the project owner is busy elsewhere and currently can't answer to requests.

Note: what do you mean by "_get as close to the jquery version of selectize as possible_"? I don't think that Selectize can do what you ask for, no?
