### ISSUE TITLE
Is there a way to use plugins?

### ISSUE THREAD

**Issue by Bana0615** [machineboy2045/angular-selectize#52]
like plugins: ['remove_button'] for example?

**Comment by miketeix** [comment]
+1

**Comment by PhiLhoSoft** [comment]
Not tried yet, but according to https://github.com/brianreavis/selectize.js/blob/master/docs/plugins.md (near the end), using a plugin is just a matter of declaring them in the config. It should work with this wrapper as well, no?

**Comment by Bana0615** [comment]
You don't implement it like that through angular

**Comment by Bana0615** [comment]
I tried to put plugins and the plugins I want to use and haven't been able
to get any working

**Comment by PhiLhoSoft** [comment]
I have a plunker I made to test my PRs against angular-selectize: http://plnkr.co/edit/8OuwS7?p=preview
I just added the line

    plugins: [ 'remove_button' ],

to two examples. I just see the remove button added to the tags.

**Comment by Bana0615** [comment]
thanks! haha i think i was using {} instead of [].
