### ISSUE TITLE
Updating model does not update selectize

### ISSUE THREAD

**Issue by donpinkus** [machineboy2045/angular-selectize#55]
Continuing from https://github.com/machineboy2045/angular-selectize/issues/47

Adding an item to the model used for options in Selectize does not change the options.

JS
```
$scope.people = [{id: 1, name: "Don"}, {id: 2, name: "John"}];

$scope.myConfig = {
    options: $scope.people,
    valueField: 'id',
    labelField: 'name',
    create: true,
    sortField: 'text',
    maxItems: 1
  }

$scope.addPerson = function(){
  $scope.people.push({ id: 3, name: "Melissa" });
}
```

HTML
```
<selectize ng-model="person" config="myConfig" placeholder='Select a person...'></selectize>

<button ng-click="addPerson()">Add Melissa</button>
```

$watch has been updated to $watchCollection in my version.

**Comment by lukasberlin** [comment]
Options that are passed via config are not bound to the scope of the directive and can thereby not be watched. Try passing the options via HTML attribute.

```HTML
<selectize ng-model="person" options="people" config="myConfig" placeholder='Select a person...'></selectize>
```

**Comment by elgs** [comment]
Passing the options via HTML attribute does not seem to work in my case. I load options from the server. The options are bound to $scope in an http callback. The options list is empty.

**Comment by elgs** [comment]
My problem was fixed by loading the list in the http callback in which options are loaded.

**Comment by mariowise** [comment]
I load the list on my service callback and options are not loaded. Can you provide some code to see the difference?

**Comment by elgs** [comment]
@mariowise I finally found my problem was the $scope. I have one `selectize` in each item in a list, and I'm updating the options from another scope which is far away. I end up updating the `selectize` using a lot of $scope.$parent.

**Comment by mariowise** [comment]
I thing I misspoke. I have a similar problem to yours. And I can't solve it... my `selectize` stays with an `[]` (empty Array) and the `options` are not updated when my service (promise) resolves. Any ideas?

**Comment by elgs** [comment]
@mariowise things get really complicated when the `$scope` come to play. I end up solving my problem with the following code:
```html
<selectize config="indexColumnConfig" options='$parent.tableColumns'
                                           data-ng-model="tableIndex.columnName"></selectize>
```

**Comment by mariowise** [comment]
oh right! was my mistake.. I was also passing the variable throw a `$parent` controller... now everything is working... Thanks!
