### ISSUE TITLE
Get an instance of the Selectize component?

### ISSUE THREAD

**Issue by donpinkus** [machineboy2045/angular-selectize#56]
When using just the Selectize JS library, you can get an instance of the component by doing this:

```
// initialize the selectize control
var $select = $('select').selectize(options);

// fetch the instance
var selectize = $select[0].selectize;
```

With angular-selectize, how can we get an instance of the component? 

I'd like to call instance methods on it (e.g. `refreshOptions()`), but I need an instance of it first.

**Comment by PhiLhoSoft** [comment]
See the README.md, Advanced Usage:

    onInitialize: function(selectize){
      // receives the selectize object as an argument
    },
