### ISSUE TITLE
Global configuration not being applied to selectize. Why?

### ISSUE THREAD

**Issue by mdmoura** [machineboy2045/angular-selectize#68]
Hello,

I used the following code to set some global configuration:

    angular.module('Application').value('selectizeConfig', {
      persist: false  
    });

But persist = false is not taken effect on my selectizes unless I set the config in the selectize itself.

Any idea why?

Thank You

**Comment by PhiLhoSoft** [comment]
I went to the official Plunker of this site, replaced the first line with:
```javascript
var app = angular.module('plunker', ['selectize']).value('selectizeConfig', {
  placeholder: 'Please choose something'  
});
```
and it worked. I could also put a placeholder in a specific config and it overrode the default.

...
Also tried with `persist: false` and it worked too.
Except the first demo has a curious behavior, sometime inputed tags are persisted, sometime not.
