### ISSUE TITLE
Can a link to remove item from selected list be added

### ISSUE THREAD

**Issue by edoarsla** [machineboy2045/angular-selectize#73]
Hi,

I'd like to add a link to each rendered item to remove it from the selected list.  Is there a way to do this?

Thank you!

**Comment by PhiLhoSoft** [comment]
Not sure if I fully understood your question, but perhaps the remove_button plugin of Selectize can do what you want.

**Comment by edoarsla** [comment]
that's exactly what I was looking for - thank you!

**Comment by PhiLhoSoft** [comment]
Then you should close this issue...
