### ISSUE TITLE
'select' is not working anymore

### ISSUE THREAD

**Issue by cybermarkus1** [machineboy2045/angular-selectize#76]
The way to get select div is not working anymore.

// initialize the selectize control
var $select = $('select').selectize(options);

// fetch the instance
var selectize = $select[0].selectize;

It seems like there is no 'select' divs available.

Help please

**Comment by PhiLhoSoft** [comment]
You are in angular-selectize, not in selectize project...

In this project, the recommended way of getting the Selectize instance is to use the onInitialize callback in the configuration.
