### ISSUE TITLE
Selecting same value more times

### ISSUE THREAD

**Issue by nedimdz** [machineboy2045/angular-selectize#79]
I use this directive for input equation, it's easy and user friendly, but for complex expression I have to use for example * more times. I looked in options but it's seems that is not supported. I wonder whether there any way for that or is there any plan for support  this behavior in future.

**Comment by PhiLhoSoft** [comment]
I had a hard time to understand your request. Do you mean that you have operators in a drop-down, and want to build a string (a math expression) by selecting items in the drop-down? Using them as tags? Interesting use... And indeed probably not covered by Selectize.
Should I have to do that, I would rather use the drop-down as single selection, and build the string in a separate input. Unless space on screen is scarce.

**Comment by nedimdz** [comment]
I found solution, add new property in config object enableDuplicate: true and change selectize.js.
var i, active, value_next, wasFull;
value = hash_key(value);

if (self.items.indexOf(value) !== -1) {
to

var enableDuplicate = self.settings.enableDuplicate;
var i, active, value_next, wasFull;
value = hash_key(value);

if ((! enableDuplicate) && (self.items.indexOf(value) !== -1)) {
