### ISSUE TITLE
Working with complex objects

### ISSUE THREAD

**Issue by ro0sterjam** [machineboy2045/angular-selectize#80]
Hi, I'm wondering if it's possible to select complex objects such as:

options = [ { id: 2, name: "Item" }];

So that "Item" is displayed as the selectable, but also once selected, the value of the model is { id: 2, name: "Item"}.

I know I can set valueField, but this results in the model having a value of simply 2, which is not what I want.

**Comment by ro0sterjam** [comment]
Perhaps there's a "format" or "onSelect" function I can set in which I can construct the object I want to set the model to?

**Comment by PhiLhoSoft** [comment]
Because of the underlying Selectize component, the model is always a list of valueField strings, alas.
Now, it is trivial to get back the full object(s) from the list of options, particularly with libraries like Lodash or Underscore (the find functions).

**Comment by PhiLhoSoft** [comment]
[**@ro0sterjam**](https://github.com/ro0sterjam) commented on [9 juin 2015 23:41 UTC+2](https://github.com/machineboy2045/angular-selectize/issues/80#issuecomment-110512478 "2015-06-09T21:41:14Z"):
> Perhaps there's a "format" or "onSelect" function I can set in which I can construct the object I want to set the model to?

See https://github.com/brianreavis/selectize.js/blob/master/docs/usage.md
What you look for is onChange or onItemAdd
