### ISSUE TITLE
ReferenceError: Selectize is not defined

### ISSUE THREAD

**Issue by swoopeh** [machineboy2045/angular-selectize#81]
I'm trying to get this to work (with requireJS) but keep getting "ReferenceError: Selectize is not defined".

Now, I'm trying to understand how this works but I can't figure it out so maybe someone can enlighten me, that would already be a great help.

The selectize plugin itself has a factory method, which uses an IIFE. We're using amd to load the modules, so the module 'selectize' gets defined as the factory method (which is the 2nd parameter of the IIFE). This means that if I define selectize in my module, I get the factory method itself and can access the "defaults" property (apologies for the coffeescript):

define [
  'selectize'
], (
  selectize
) ->
  console.log selectize.defaults

This properly outputs the defaults, no problems so far. However, when I look in the angular-selectize script, the first line in the "link" function is:

Selectize.defaults.maxItems = null; //default to tag editor

However, since Selectize isn't defined in this scope (nor in a parent scope) this throws an error. I'm just not sure how this is supposed to work; as far as I can see the variable "Selectize" is only defined inside the selectize factory method and as such isn't globally available, so I'm assuming this has to come from somewhere else, I just don't see where.

**Comment by PhiLhoSoft** [comment]
Angular-Selectize assumes Selectize is loaded globally, with just a `<script>` tag loading it in the `index.html` of the application. That's how we (and most other people, I guess) we use it.
You might need some adjustments to make the directive to behave nicely with AMD / CommonJS.

**Comment by eMerzh** [comment]
i might be wrong, but i have the same pbm, 
i got the all the <script> in the same place, jquery, selectize, angular, angular-selectize, my scripts,

if i use $(element) on line 117 it works, but i don't think it's a good idea

**Comment by shprota** [comment]
To workaround this issue you can put this line in the controller responsible for a view containing <selectize> tag:
window.Selectize = require('selectize');

**Comment by ahmadassaf** [comment]
@swoopeh I have had the same issue and managed to figure things out. The following is the directive i am using which uses require.js to load jquery and selectize.

In my `main.js`

```javascript
require.config({
    paths: {
        'angular'                 : '../lib/angular/angular',
        'jquery'                  : '../lib/jquery/dist/jquery.min',
        'selectize'               : '../components/js/selectize/dist/js/standalone/selectize.min',
        ......
    },
```

here i load jQuery and notice that i load the `selectize` **standalone** version that has all its dependencies.

Afterwards, i have a directive defined as:

```javascript
define(['./module', 'jquery', 'selectize'], function(directives, $, Selectize) {

	'use strict';

	// This will control the show/hide of elements based on the access level defined in the directive

	directives.directive('selectize', function() {
		return {
			restrict: 'EA',
			require : '^ngModel',
			scope: {
				ngModel   : '=',
				config    : '=?',
				options   : '=?',
				ngDisabled: '=',
				ngRequired: '&'
			},
			link: function(scope, element, attrs, modelCtrl) {

				Selectize.defaults.maxItems = null; //default to tag editor

				var selectize,
					config = angular.extend({}, Selectize.defaults, scope.config);

				modelCtrl.$isEmpty = function(val) {
					return val === undefined || val === null || !val.length; //override to support checking empty arrays
				};

				function createItem(input) {
					var data = {};
					data[config.labelField] = input;
					data[config.valueField] = input;
					return data;
				}

				function toggle(disabled) {
					disabled ? selectize.disable() : selectize.enable();
				}

				var validate = function() {
					var isInvalid = (scope.ngRequired() || attrs.required || config.required) && modelCtrl.$isEmpty(scope.ngModel);
					modelCtrl.$setValidity('required', !isInvalid);
				};

				function generateOptions(data) {

					if (!data)
						return [];

					data = angular.isArray(data) || angular.isObject(data) ? data : [data]

					return $.map(data, function(opt) {
						return typeof opt === 'string' ? createItem(opt) : opt;
					});
				}

				function updateSelectize() {

					validate();

					selectize.$control.toggleClass('ng-valid', modelCtrl.$valid);
					selectize.$control.toggleClass('ng-invalid', modelCtrl.$invalid);
					selectize.$control.toggleClass('ng-dirty', modelCtrl.$dirty);
					selectize.$control.toggleClass('ng-pristine', modelCtrl.$pristine);

					if (!angular.equals(selectize.items, scope.ngModel)) {
						selectize.addOption(generateOptions(scope.ngModel));
						selectize.setValue(scope.ngModel);
					}
				}

				var onChange = config.onChange,
					onOptionAdd = config.onOptionAdd;

				config.onChange = function() {

					if (scope.disableOnChange)
						return;

					if (!angular.equals(selectize.items, scope.ngModel))
						scope.$evalAsync(function() {
							var value = angular.copy(selectize.items);
							if (config.maxItems == 1) {
								value = value[0]
							}
							modelCtrl.$setViewValue(value);
						});

					if (onChange) {

						onChange.apply(this, arguments);
					}
				};

				config.onOptionAdd = function(value, data) {
					if (scope.options.indexOf(data) === -1) {
						scope.options.push(data);

						if (onOptionAdd) {
							onOptionAdd.apply(this, arguments);
						}
					}
				};

				if (scope.options) {
					// replace scope options with generated options while retaining a reference to the same array
					scope.options.splice(0, scope.options.length, generateOptions(scope.options));
				} else {
					// default options = [ngModel] if no options specified
					scope.options = generateOptions(angular.copy(scope.ngModel));
				}

				var angularCallback = config.onInitialize;

				config.onInitialize = function() {
					selectize = $(element)[0].selectize;
					selectize.addOption(scope.options);
					selectize.setValue(scope.ngModel);

					//provides a way to access the selectize element from an
					//angular controller
					if (angularCallback) {
						angularCallback(selectize);
					}

					scope.$watch('options', function() {
						selectize.clearOptions();
						selectize.addOption(scope.options);
						selectize.setValue(scope.ngModel);
					}, true);

					scope.$watchCollection('ngModel', updateSelectize);
					scope.$watch('ngDisabled', toggle);
				};

				$(element).selectize(config);

				$(element).on('$destroy', function() {
					if (selectize) {
						selectize.destroy();
						element = null;
					}
				});
			}
		};
	});
});
```

Note also that i wrap `element` with the jQuery selector `$` or else you will get some errors also.

**Comment by rakfali** [comment]
Hi all. I am new to require. I am facing the same issue. Actually I am changing my project from normal angular to require with angular. I am facing the same issue of the angular-selectize.

@shprota : I have tried your way but it is not working for me. May be there is some issue at my end to initialize this.

@ahmadassaf : I have tried but still I am not able to make it functional. Can you please explain me little bit more. I am new in this. If you can give me more detail so that I can resolve my issue.

require.config({
    baseurl: '/scripts/',
 paths: {
        'angular': 'libs/angular',
        'ngStorage': 'libs/ngStorage',
        'ngCookies': 'libs/angular-cookies',
        'ngAnimate': 'libs/angular-animate.min',
        'ngSanitize': 'libs/angular-sanitize',
        'ui-router': 'libs/angular-ui-router',
        'jquery': 'libs/jquery-1.10.2',
        'jquery-ui': 'libs/jquery-ui.min',
        'bootstrap': 'libs/bootstrap',
        'route': 'routes/routeConfig',
        'toaster': 'libs/angular-toaster/toaster',
        'jselectize': 'libs/Angular-Selectize/selectize',
        'selectize': 'libs/Angular-Selectize/angular-selectize',
 },
    shim: {
            'selectize': {
                     deps: ['jquery', 'angular', 'jselectize']
             }
},
    deps: ['app']
});

require([
    "app",
    "ngCookies",
    "route",
    "jquery",
    "jquery-ui",
    "bootstrap",
    "ngAnimate",
    //"selectize",
    "ngSanitize",
    "toaster",
    "selectize"
], 
function (app) {
        //bootstrapping app
        app.init();
    }
);

**Comment by ahmadassaf** [comment]
@rakfali Hey man. My solution have a custom directive that i changed a bit and is pasted above. 

What i have included in the `app.js` is the path to the normal non-angular `selectize`. Then try to use the directive i have pasted above.

Tell me if you need more details

**Comment by salmanasiddiqui** [comment]
Why is this issue closed? isn't the issue is still present when used with AMD/requireJS? Anyone using the solution posted by @ahmadassaf will require to update their directive whenever a new version of angular-selectize2 is released.
