### ISSUE TITLE
is there an onChange like callback available?

### ISSUE THREAD

**Issue by anatoliyg** [machineboy2045/angular-selectize#82]

**Comment by PhiLhoSoft** [comment]
You should read the [Selectize docs](https://github.com/brianreavis/selectize.js/blob/master/docs/usage.md)...

**Comment by ebarroso** [comment]
There is an onChange callback but in the current versions is being called twice... So not very useful for all use cases

**Comment by PhiLhoSoft** [comment]
The double call has been fixed in the latest version.
