### ISSUE TITLE
How to reload options?

### ISSUE THREAD

**Issue by elgs** [machineboy2045/angular-selectize#83]
I want to programmatically reload the options when the underlying data changed. Is there a way to reload the options? Thanks.

**Comment by PhiLhoSoft** [comment]
See https://github.com/brianreavis/selectize.js/blob/master/docs/api.md (addOption, accepts an array).

**Comment by elgs** [comment]
Thanks @PhiLhoSoft, but how can I invoke addOption? There seems to be not any angular-selectize variable in my controller.

**Comment by PhiLhoSoft** [comment]
Search onInitialize on the home page of this project, read the comment.

**Comment by elgs** [comment]
Thanks @PhiLhoSoft. So if I want to use it in another function, should I hook the variable `selectize` to another variable outside the `onInitialize`, like so?

```
var mySelectize = 
$scope.myConfig = {
  // ...
  onInitialize: function(selectize){
    // receives the selectize object as an argument
    mySelectize = selectize;
  }
};
```

Is it correct? Thanks.

**Comment by PhiLhoSoft** [comment]
Yes, that's how we do it. But all access to the Selectize object is done in a service, to isolate usage of a Dom-dependent component.

**Comment by elgs** [comment]
Got thank you so much @PhiLhoSoft.
