### ISSUE TITLE
Add options in which the JSON comes from HTTP request

### ISSUE THREAD

**Issue by danimm** [machineboy2045/angular-selectize#86]
I get a JSON which I would add the options, it works perfectly when you use only the Selectize.js library. I don't get any errors but when selecting not appear no option (is empty). Can someone help me?
``` 
 function getArray(){
  try{
  agenciasAPI.getAgencias().success(function (data){
    return data._embedded.agencias;
  }).catch(function (error){
    alert(error + "\t" + JSON.stringify(error));
  });
}catch(err){
  alert(err);
}
}
  $scope.single = null;
  $scope.myOptions = getArray();
    $scope.singleConfig = {
      create: false,
      valueField: 'nome',
      labelField: 'nome',
      maxItems: 1
    }
```

HTML
```
<selectize placeholder='Select a person...' config="singleConfig" ng-model="single" options="myOptions"></selectize>
```
![screenshot from 2015-07-22 12 17 38](https://cloud.githubusercontent.com/assets/8279779/8829207/c5d0a082-306b-11e5-831a-ed3e725ae6d3.png)

**Comment by PhiLhoSoft** [comment]
getArray() doesn't return anything...
You should get familiarized with asynchronous requests.
The success() function should be:

```
.success(function (data){
    $scope.myOptions = data._embedded.agencias;
  })
```

**Comment by danimm** [comment]
I am having several errors in the project because of that, I forget the asynchronous
Thanks @PhiLhoSoft
