### ISSUE TITLE
v1.2.3 fails to get options from config object

### ISSUE THREAD

**Issue by serjrd** [machineboy2045/angular-selectize#92]
Everything works fine in v1.2.2.
I take it, this is because in your latest commit you forgot to mention `config.options` variable.

**Comment by machineboy2045** [comment]
Dropping support for options in the config object was intentional. It simplified the codebase.

**Comment by serjrd** [comment]
I see. The docs need an update then.
And it's probably a good idea to create a CHANGELOG file to reflect changes like that.

And by the way - thanks for all your work on this project :)

**Comment by machineboy2045** [comment]
I think you're right about the CHANGELOG. 

Where is the documentation out of date? I don't see a reference to config.options but i might just be missing it

**Comment by serjrd** [comment]
This is what confused me: https://github.com/brianreavis/selectize.js/blob/master/docs/usage.md
It lists 'options' as one of the possible config object items.

**Comment by machineboy2045** [comment]
I see. I'll add a note to the README about it
