### ISSUE TITLE
Selectize.ClearOptions() doesn't work when loading data dynamically.

### ISSUE THREAD

**Issue by Karankang007** [machineboy2045/angular-selectize#94]
Since angular-selectize doesn't listen for selectize clear event, the options in directive memory become stale if selectize.clearOptions() is called.

Due to this, new data keeps getting appended to the existing options.

**Comment by Karankang007** [comment]
Pull request https://github.com/machineboy2045/angular-selectize/pull/95 should fix this issue

**Comment by rob-balfre** [comment]
I get TypeError: element.selectize is not a function with this fix

**Comment by dlaviati** [comment]
Same issue here and the suggested fix works perfectly for me.

**Comment by machineboy2045** [comment]
Hmm.. my thought so far is that users should be using angular to manipulate their options. They shouldn't be calling selectize.clearOptions(). They should use $scope.options = []. So the directive shouldn't need to listen for that event.

**Comment by Karankang007** [comment]
If the user is loading data from remote source, they don't have direct access to $scope.options. Also, the original library has the functionality of clearing options, I think angular-selectize should too.

**Comment by machineboy2045** [comment]
Again, if the data is a remote source, it should be loaded in an Angular controller, and assigned to the Angular model.

**Comment by Karankang007** [comment]
The data loading is not the problem here, the problem is once the loaded data is cleared, the value of $scope.options variable in this directive doesn't match the source data inside the selectize library.

**Comment by machineboy2045** [comment]
Since this is an Angular directive, the expectation is that the user will rely on Angular for loading options. 
`$http.get(remoteURL, function(data){
    $scope.options = data;
  })
`
