### ISSUE TITLE
Selectize Tagging  dosent work in new version 3

### ISSUE THREAD

**Issue by programming-kid** [machineboy2045/angular-selectize#99]
Hello

i recently updated angular-selectize to latest  version but then selectize tagging stopped working altogether i couldn't  figure out what happened but when i reverted back to v1.2.3 it started working again
here is config i am using for selectize tagging 

```javascript
{
create: true,
maxItems: 5,
 delimiter: ',',
 placeholder: 'Describe campaign in keywords '
}
```

pls help

**Comment by machineboy2045** [comment]
Check your Browser console for JS errors. Tagging should work. The 'Demo'
link on my github uses the latest version. And I don't see anything wrong
with your config

**Comment by programming-kid** [comment]
After a investigating for two hours i was able to replicate my issue in this plunker http://plnkr.co/edit/7m0TZMu5ejmiZg0WHerW?p=preview  it is caused by using selectize in input

**Comment by programming-kid** [comment]
Also is there any way to get it working with ```ng-messages``` as it cant work with ```input``` element so it wont also work with ```ng-messages```

**Comment by machineboy2045** [comment]
It's not meant to work with <input></input>. It has to be <selectize></selectize>

Sorry, I'm not familiar with ng-messages.

**Comment by programming-kid** [comment]
But how can i use ng-required if i don't have ```name``` attribute to show error messages

**Comment by machineboy2045** [comment]
you can do <selectize name='myName'></selectize>. I tested it and added it
to the demo: http://plnkr.co/edit/nTf19f?p=preview
